replicaCount: 1
groupName: train-regist
projectName: train-regist-admin
image:
  repository: harbor.prod.k8s.lesso.com/operation-train-regist/train-regist-admin
  docsRepository: harbor.prod.k8s.lesso.com/operation-train-regist/train-regist-admin-docs
  pullPolicy: Always
deployment:
  web:
    enable: true
  web_docs:
    enable: true
service:
  web:
    name: train-regist-admin
    enable: true
    type: ClusterIP
    port: 80
  web_docs:
    name: train-regist-admin-docs
    enable: true
    type: ClusterIP
    port: 80
ingress:
  web:
    enable: true
    host: train-regist.train-regist-admin.172.16.90.27.xip.io
  web_docs:
    enable: true
    host: train-regist.train-regist-admin-docs.172.16.90.27.xip.io
env:
  open:
    PRO_API_HOST: api.prod.k8s.lesso.com
logs:
  parser: nginx
matchExpressions:
  key: host-role-app
  values:
    - dev-work-app
resources:
  requests:
    memory: 300Mi
    cpu: 100m
  limits:
    memory: 500Mi
    cpu: 200m
